### ISSUE TITLE
Default branch for this lesson:  gh_pages or add_content?

### ISSUE THREAD

**Issue by amanmdesai** [hsf-training/hsf-training-ml-gpu-webpage#14]
<details>
<summary><strong>Instructions</strong></summary>

Thanks for contributing! :heart:

If this issue is about a specific episode within a lesson, please provide its link or filename.

Keep in mind that **lesson maintainers are volunteers** and it may take them some time to respond to your contribution.
To ensure that the right people get notified, you can tag some of the last contributors with `@githubname`.

Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum. If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact the HSF training convenors ([contacts here](https://hepsoftwarefoundation.org/workinggroups/training.html)).

You may delete these instructions from your issue.

\- HSF Training
</details>

**Comment by amanmdesai** [comment]
pinging @klieret

**Comment by amanmdesai** [comment]
If one clicks the link (edit on github) given below in the episodes, it opens up the add_content branch. Secondly the episodes in add_content branch are quite different from gh_pages (gh_pages is rendered on the website).

**Comment by klieret** [comment]
Yeah, I stumbled on this before, too....

Do you know which version the videos correspond to?

**Comment by klieret** [comment]
urgh yeah, I just saw that `add_content` is the default branch, but not the branch that the website is deployed from. What a mess :/

**Comment by amanmdesai** [comment]
> Yeah, I stumbled on this before, too....
> 
> Do you know which version the videos correspond to?

I just now checked 1-2 videos (setup/intro), it seems they are same as the website (gh_pages)

**Comment by wdconinc** [comment]
Solved by #25.
