### ISSUE TITLE
Move to use Jekyll theme

### ISSUE THREAD

**Issue by klieret** [hsf-training/hsf-training-ml-gpu-webpage#15]

**Comment by amanmdesai** [comment]
Hi @klieret ,

I think this issue is resolved with #22, right?

**Comment by klieret** [comment]
no, this means using the [jekyll theme](github.com/hsf-training/hsf-training-theme) rather than duplicating all style files in this repository

**Comment by amanmdesai** [comment]
> no, this means using the [jekyll theme](github.com/hsf-training/hsf-training-theme) rather than duplicating all style files in this repository

Oh I see.
