### ISSUE TITLE
Add bonus episode on using tensorflow 

### ISSUE THREAD

**Issue by amanmdesai** [hsf-training/hsf-training-ml-gpu-webpage#16]
<details>
<summary><strong>Instructions</strong></summary>

Thanks for contributing! :heart:

If this issue is about a specific episode within a lesson, please provide its link or filename.

Keep in mind that **lesson maintainers are volunteers** and it may take them some time to respond to your contribution.
To ensure that the right people get notified, you can tag some of the last contributors with `@githubname`.

Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum. If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact the HSF training convenors ([contacts here](https://hepsoftwarefoundation.org/workinggroups/training.html)).

You may delete these instructions from your issue.

\- HSF Training
</details>

**Comment by amanmdesai** [comment]
@klieret this can be tagged as either `good first issue` or `issue for hacktoberfest`. 
what do you think?

(basic tensorflow was included in the intro to ml, but is missing here)

**Comment by klieret** [comment]
Hmm, I think that the lesson should rather pick one of the two. And `pytorch` seems to be the one that is more popular in academia right now.

**Comment by amanmdesai** [comment]
Oh by "lesson" I meant one episode on using tensorflow with gpu. 
So one episode that includes only tensorflow, while rest of the module is on pytorch.

Like this:
https://hsf-training.github.io/hsf-training-ml-webpage/13-TensorFlow/index.html
